spring:
  application:
    name: swe-adapter
  banner:
    location: banner.txt
  rabbitmq:
    username: gridcapa
    password: gridcapa
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        consumeTask-in-0:
          binder: rabbit
          destination: swe-d2cc-run-task
      rabbit:
        default:
          consumer:
            auto-bind-dlq: true
            max-attempts: 1
    function:
      definition: consumeTask

logback:
  amqp:
    exchange: swe-d2cc-task-manager-logs-exchange
    routing-key: "#"

swe-adapter:
  process-type: D2CC

swe-runner:
  binding:
    destination: swe-d2cc-request

minio-adapter:
  bucket: gridcapa
  base-path:
  access-key: gridcapa
  secret-key: gridcapa
  url: http://localhost:9000